# hypothesize that we haven't saturized performance with trivial feature engineering using EHR. This is less exciting but I think if the goal is to be most useful': None, ' this is very important. 
# this is for generating features for input': None, ' labeling': None, ' visualizing': None, ' and creating group based / stratified splits. modular where can use various dates of interest
# maximium code sharing between different types of EHR and also different diseases. Really tried to simplify so that the code is readable and create a nice API. where people only need to interact with the config file basically to generate all these functions.

# future work: interested in doing both detection and prediction in the same network. I think there's value in just looking through the large amount of patient data quickly and identifiying issues. In this vein there's other diesease such as abdominal aortic anyurisms that I'm 

TRUNCATE:
  PATH: /bmrNAS/scandata/abct_ehr/clinical_data/
  SAVE_DIR: /dataNAS/people/lblankem/opportunistic_ct/libraries/stanford_extract/stanford_extract/truncated/
  NUM_PATIENTS: 25000
  DATES: 'CT'
  TYPES:
    DEMOGRAPHICS: 
      USE: False
      FILE_NAME: "demographics.csv"
      USE_COLS: ['Patient Id', 'Gender', 'Race', 'Ethnicity', 'Date of Birth']
    VITALS: 
      USE: True
      FILE_NAME: "flowsheets.csv"
      USE_COLS: ['Patient Id', 'Measure', 'Value', 'Date']
    LABS: 
      USE: False
      FILE_NAME: "labs.csv"
      USE_COLS: ['Patient Id', 'Value', 'Taken Date', 'Result', 'Reference High', 'Reference Low', 'Units']
    DIAGNOSES:
      USE: False
      FILE_NAME: "diagnoses.csv"
      USE_COLS: ['Patient Id', 'Date', 'ICD10 Code']
    PROCEDURES:
      USE: False
      FILE_NAME: "procedures.csv"
      USE_COLS: ['Patient Id', 'Code Type', 'Code', 'Date']
    MED_ORDERS:
      USE: False
      FILE_NAME: "med_orders.csv"
      #USE_COLS: ['Patient Id', 'Therapeutic Class', 'Sig', 'Start Date']
    MED_ADMIN:
      USE: False
      FILE_NAME: "med_admin.csv"
    RADIOLOGY_REPORT_META:
      USE: False
      FILE_NAME: "radiology_report_meta.csv"
    CLINICAL_NOTE_META:
      USE: False
      FILE_NAME: "clinical_note_meta.csv"
    ENCOUNTERS:
      USE: False
      FILE_NAME: "encounters.csv"
    
FEATURES:
  SAVE_DIR: /bmrNAS/scandata/abct_ehr/clinical_data/truncated_v1/
  NUM_PATIENTS: 23547
  DATES: 'CT'
  LAG_AFTER_DATES: 14
  TYPES:
    DEMOGRAPHICS: 
      USE: True
      FILE_NAME: "demographics.csv"
      USE_COLS: ['Patient Id', 'Gender', 'Race', 'Ethnicity', 'Date of Birth']
      INCLUDE: {'Gender': None, 'Race': None, 'Ethnicity': None, 'Date of Birth': None} # Date of Birth here gets converted to age.
      BINS: 1
      BIN_DURATION: 1 #in years
      AGGREGATE: 'mean'
      FILL_NA: 'median'
      SAVE: True
      LOAD: True
    VITALS: 
      USE: True
      FILE_NAME: "flowsheets.csv"
      USE_COLS: ['Patient Id', 'Measure', 'Value', 'Date']
      TYPE: 'Measure'
      VALUE: 'Value'
      INCLUDE: {'DBP': None, 'SBP': None, 'BP': None, 'Pulse': None, 'Temp': None, ' Weight': None, 'SpO2': None, 'Resp': None, 'Mean Arterial Pressure \(Calculated\)': None, 'BSA \(Calculated - sq m\)': None, ' Height': None, ' Fall Within Last 6 Months': None}
      BINS: 1
      BIN_DURATION: 1
      AGGREGATE: 'mean'
      FILL_NA: 'median'
      SAVE: True
      LOAD: True
    LABS: 
      USE: True
      FILE_NAME: "labs.csv"
      USE_COLS: ['Patient Id', 'Value', 'Taken Date', 'Result', 'Reference High', 'Reference Low', 'Units']
      TYPE: 'Result'
      Value: 'Value'
      INCLUDE: {'^HDL Cholesterol': 'HDL Cholesterol', 'Cholesterol, Total': 'Cholesterol, Total', 'Creatinine, Ser/Plas': None, 'Potassium, Ser/Plas': None, 'Hematocrit': None, 'Hemoglobin': None, 'Glucose, Ser/Plas': None, 'WBC': None, 'RBC': None, 'Calcium, Ser/Plas': None, 'MCHC': None, 'RDW': None, 'MCV': None, 'MCH': None, 'Platelet count': None, 'CO2, Ser/Plas': None, 'Sodium, Ser/Plas': None, 'Chloride, Ser/Plas': None, 'Anion Gap': None, 'Albumin, Ser/Plas': None, 'ALT \(SGPT\), Ser/Plas': None, 'AST \(SGOT\), Ser/Plas': None, 'Alk P': None, 'Protein, Total, Ser/Plas': None, 'Globulin': None, 'RBC, urine': None, 'WBC, urine': None, 'BUN, Ser/Plas': None, 'eGFR Refit Without Race \(2021\)': None, 'Total Bilirubin, Ser/Plas': None, 'Lymphocyte, Absolute': None, 'Lymphocyte %': None, 'Monocyte, Absolute': None, 'Basophil %': None, 'Basophil, Absolute': None, 'Monocyte %': None, 'Eosinophil, Absolute': None, 'Eosinophil %': None, 'Neutrophil, Absolute': None, 'Neutrophil %': None, 'Heart Rate': None, 'QT Interval': None, 'QRSD Interval': None, 'QRS Axis': None, 'ECG Impression': None, 'RR': None, 'QTC Interval': None, 'T Wave Axis': None, 'P-R Interval': None, 'P Axis': None, 'Total Bilirubin': None, 'Hemoglobin A1c': None}
      BINS: 1
      BIN_DURATION: 1 
      AGGREGATE: 'mean'
      FILL_NA: 'median'
      SAVE: True
      LOAD: True
    DIAGNOSES:
      USE: True
      FILE_NAME: "diagnoses.csv"
      USE_COLS: ['Patient Id', 'Date', 'ICD10 Code']
      TYPE: 'ICD10 Code'
      NUM_ICD_CHARS: 3
      BINS: 1
      BIN_DURATION: 1
      AGGREGATE: 'sum'
      FILL_NA: '0'
      SAVE: True
      LOAD: True
    PROCEDURES:
      USE: True
      FILE_NAME: "procedures.csv"
      USE_COLS: ['Patient Id', 'Code Type', 'Code', 'Date']
      TYPE: 'Code'
      BINS: 1
      BIN_DURATION: 1 #in years
      AGGREGATE: 'sum'
      FILL_NA: '0'
      SAVE: True
      LOAD: False
    MED_ORDERS:
      USE: True
      FILE_NAME: "med_orders.csv"
      USE_COLS: ['Patient Id', 'Therapeutic Class', 'Sig', 'Start Date']
      TYPE: 'Therapeutic Class'
      BINS: 1
      BIN_DURATION: 1
      AGGREGATE: 'mean'
      FILL_NA: '0'
      SAVE: True
      LOAD: False
    MED_ADMIN:
      USE: False
      FILE_NAME: "med_admin.csv"
      BINS: 1
      BIN_DURATION: 1
      AGGREGATE: 'sum'
      SAVE: True
      LOAD: False
    RADIOLOGY_REPORT_META:
      USE: False
      FILE_NAME: "radiology_report_meta.csv"
      BINS: 1
      BIN_DURATION: 1
      AGGREGATE: 'mean'  
      SAVE: True
      LOAD: True
    CLINICAL_NOTE_META:
      USE: False
      FILE_NAME: "clinical_note_meta.csv"
      BINS: 1
      BIN_DURATION: 1
      AGGREGATE: 'sum'
      SAVE: True
      LOAD: True
    ENCOUNTERS:
      USE: False
      FILE_NAME: "encounters.csv"
      BINS: 1
      BIN_DURATION: 1
      AGGREGATE: 'mean'
      SAVE: True
      LOAD: True




