DATA_PATH: /bmrNAS/scandata/abct_ehr/clinical_data/
SAVE_DIR: /dataNAS/people/lblankem/STARR-Labeler/starr_labeler/features/results
NUM_PATIENTS: 23547
PREDICTION_DATES: 'CT'
DAYS_AFTER_PREDICTION_DATES: 14
EHR_TYPES:
  DEMOGRAPHICS: 
    FILE_NAME: "demographics.csv"
    REGEX_TO_FEATURE_NAME: {'Gender': None, 'Race': None, 'Ethnicity': None, 'Date of Birth': None} # Date of Birth here gets converted to age.
    TIME_BINS: 1
    TIME_BIN_DURATION: 1 # in years
    AGGREGATE_ACROSS_TIME: 'mean'
    FILL_NA: 'median'
    USE: True
    USE_TRUNCATED: True
    SAVE_TRUNCATED: False
    SAVE: True
    LOAD: False
  VITALS: 
    FILE_NAME: "flowsheets.csv"
    TYPE: 'Measure'
    # REGEX_TO_FEATURE_NAME: {'DBP': None, ' SBP': None, ' BP': None, ' Pulse': None, ' Temp': None, ' Weight': None, ' SpO2': None, ' Resp': None, ' Mean Arterial Pressure (Calculated)': None, ' BSA (Calculated - sq m)': None, ' Height': None, ' Fall Within Last 6 Months': None}
    REGEX_TO_FEATURE_NAME: {'SBP': None}
    TIME_BINS: 1
    TIME_BIN_DURATION: 1 #in years
    AGGREGATE_ACROSS_TIME: 'pce'
    FILL_NA: 'median'
    USE: True
    SAVE: True
    LOAD: False
  LABS: 
    FILE_NAME: "labs.csv"
    TYPE: 'Result'
    # REGEX_TO_COLUMN_LABEL: {'HDL Cholesterol': None, ' Cholesterol, Total': None, ' Creatinine': None, ' Ser/Plas': None, ' Potassium': None, ' Ser/Plas': None, ' Hematocrit': None, ' Hemoglobin': None, ' Glucose': None, ' Ser/Plas': None, ' WBC': None, ' RBC': None, ' Calcium': None, ' Ser/Plas': None, ' MCHC': None, ' RDW': None, ' MCV': None, ' MCH': None, ' Platelet count': None, ' CO2': None, ' Ser/Plas': None, ' Sodium': None, ' Ser/Plas': None, ' Chloride': None, ' Ser/Plas': None, ' Anion Gap': None, ' Albumin': None, ' Ser/Plas': None, ' ALT (SGPT)': None, ' Ser/Plas': None, ' AST (SGOT)': None, ' Ser/Plas'': None, ' "Alk P'TASE': None, ' Total': None, ' Ser/Plas"': None, ' 'Protein': None, ' Total': None, ' Ser/Plas': None, ' Globulin': None, ' RBC': None, ' urine': None, ' WBC': None, ' urine': None, ' BUN': None, ' Ser/Plas': None, ' eGFR Refit Without Race (2021)': None, ' Total Bilirubin': None, ' Ser/Plas': None, ' Lymphocyte': None, ' Absolute': None, ' Lymphocyte %': None, ' Monocyte': None, ' Absolute': None, ' Basophil %': None, ' Basophil': None, ' Absolute': None, ' Monocyte %': None, ' Eosinophil': None, ' Absolute': None, ' Eosinophil %': None, ' Neutrophil': None, ' Absolute': None, ' Neutrophil %': None, ' Heart Rate': None, ' QT Interval': None, ' QRSD Interval': None, ' QRS Axis': None, ' ECG Impression': None, ' RR': None, ' QTC Interval': None, ' T Wave Axis': None, ' P-R Interval': None, ' P Axis': None, ' Total Bilirubin': None, ' Hemoglobin A1c': None}
    # For PCE:
    REGEX_TO_FEATURE_NAME: {'^HDL Cholesterol': 'HDL Cholesterol', 'Cholesterol, Total': 'Cholesterol, Total'}
    TIME_BINS: 1
    TIME_BIN_DURATION: 1 #in years
    # AGGREGATE_ACROSS_TIME: 'mean'
    AGGREGATE_ACROSS_TIME: 'pce'
    FILL_NA: 'median'
    USE: True
    SAVE: True
    LOAD: False
  DIAGNOSES:
    FILE_NAME: "diagnoses.csv"
    TYPE: 'ICD10 Code'
    # For PCE:
    REGEX_TO_FEATURE_NAME: {'F17.210': None, 'Z72.0': None, 'E08': None, 'E09': None, 'E10': None, 'E11': None, 'E13'}
    NUM_ICD_CHARS: 3
    TIME_BINS: 1
    TIME_BIN_DURATION: 1 # in years
    AGGREGATE_ACROSS_TIME: 'mean'
    FILL_NA: '0'
    USE: True
    SAVE: True
    LOAD: False
  PROCEDURES:
    FILE_NAME: "procedures.csv"
    TYPE: 'Code'
    TIME_BINS: 1
    TIME_BIN_DURATION: 1 # in years
    AGGREGATE_ACROSS_TIME: 'sum'
    FILL_NA: '0'
    USE: False
    SAVE: True
    LOAD: False
  MED_ORDERS:
    FILE_NAME: "med_orders.csv"
    TYPE: 'Therapeutic Class'
    #For CPE
    REGEX_TO_FEATURE_NAME: {'blood pressure': None}
    TIME_BINS: 1
    TIME_BIN_DURATION: 1
    AGGREGATE_ACROSS_TIME: 'mean'
    FILL_NA: '0'
    USE: True
    SAVE: True
    LOAD: False
  MED_ADMIN:
    FILE_NAME: "med_admin.csv"
    TIME_BINS: 1
    TIME_BIN_DURATION: 1
    AGGREGATE_ACROSS_TIME: 'sum'
    USE: False
    SAVE: True
    LOAD: False
  RADIOLOGY_REPORT_META:
    FILE_NAME: "radiology_report_meta.csv"
    TIME_BINS: 1
    TIME_BIN_DURATION: 1
    AGGREGATE_ACROSS_TIME: 'mean'
    USE: False
    SAVE: True
    LOAD: True
  CLINICAL_NOTE_META:
    FILE_NAME: "clinical_note_meta.csv"
    TIME_BINS: 1
    TIME_BIN_DURATION: 1
    AGGREGATE_ACROSS_TIME: 'sum'
    USE: False
    SAVE: True
    LOAD: True
  ENCOUNTERS:
    FILE_NAME: "encounters.csv"
    TIME_BINS: 1
    TIME_BIN_DURATION: 1
    AGGREGATE_ACROSS_TIME: 'mean'
    USE: False
    SAVE: True
    LOAD: True
